<?php

namespace B2B\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostAttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostAttributeRepository extends EntityRepository
{
}
