<?php

namespace B2B\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Validator\Constraints\Type;

/**
 * PostMetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostMetaRepository extends EntityRepository
{

    public function getCount($id)
    {
        $qb = $this->createQueryBuilder('meta');
        $query = $qb->select('meta.postId, meta.value');
        if (is_array($id)) {
            $query->where($qb->expr()->in('meta.postId', $id));
        } else {
            $query->where('meta.postId = :id')
                ->setParameter(':id', $id);
        }

        return $query->getQuery()->getResult();
    }
}
