company:
    pattern:  /company/{i}
    defaults: { _controller: B2BBlogBundle:Company:index }
    
products:
    pattern:  /products/{i}
    defaults: { _controller: B2BBlogBundle:Products:index }

companyprod:
    pattern:  /companyprod/{id}
    defaults: { _controller: B2BBlogBundle:Companyprod:index }
info:
     pattern: /info/{i}
     defaults: { _controller: B2BBlogBundle:Info:index }
infoarticle:
    pattern: /infoarticle/{i}
    defaults: { _controller: B2BBlogBundle:Infoarticle:index }


