AppBundle\Entity\Admin:
    repositoryClass: AppBundle\Entity\AdminRepository
    type: entity
    table: admin
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    lifecycleCallbacks: {  }
