AppBundle\Entity\Articles:
    repositoryClass: AppBundle\Entity\ArticlesRepository
    type: entity
    table: articles
    indexes:
        Articles_0316dde1:
            columns:
                - company_id
        Articles_80c06cbb:
            columns:
                - last_modified_user_id
        Articles_406ec824:
            columns:
                - stampdevice_id
        Articles_ffaba1d1:
            columns:
                - subject_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        companyId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: company_id
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        body:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        created:
            type: datetime
            nullable: false
        description:
            type: string
            nullable: false
            length: 400
            options:
                fixed: false
        tags:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        published:
            type: boolean
            nullable: false
        lastModifiedUserId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: last_modified_user_id
        image:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        swdelete:
            type: boolean
            nullable: false
        stampdate:
            type: datetime
            nullable: false
        stampdeviceId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: stampdevice_id
        subjectId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: subject_id
        views:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
    lifecycleCallbacks: {  }
