AppBundle\Entity\Companies:
    repositoryClass: AppBundle\Entity\CompaniesRepository
    type: entity
    table: companies
    indexes:
        Companies_d860be3c:
            columns:
                - CountryC
        Companies_b376980e:
            columns:
                - CityC
        Companies_a3c9d75e:
            columns:
                - CompanyType
        Companies_494063b5:
            columns:
                - DefaultCustomer
        Companies_5da967c3:
            columns:
                - DefaultCashier
        Companies_4d5ba1a7:
            columns:
                - DefaultIncomeVAT
        Companies_406ec824:
            columns:
                - StampDevice
        Companies_4c1c18be:
            columns:
                - DefaultItem
        Companies_75a9a664:
            columns:
                - DefaultImporter
        Companies_85ab9a21:
            columns:
                - DefaultManufacturer
    id:
        c:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: C
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: Email
        password:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: Password
        nm:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: Nm
        dateclose:
            type: datetime
            nullable: true
            column: DateClose
        countryc:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: CountryC
        cityc:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CityC
        address:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: Address
        phoneareacode:
            type: string
            nullable: false
            length: 3
            options:
                fixed: false
            column: PhoneAreaCode
        phonenumber:
            type: string
            nullable: false
            length: 12
            options:
                fixed: false
            column: PhoneNumber
        mobileareacode:
            type: string
            nullable: false
            length: 3
            options:
                fixed: false
            column: MobileAreaCode
        mobilenumber:
            type: string
            nullable: false
            length: 12
            options:
                fixed: false
            column: MobileNumber
        faxareacode:
            type: string
            nullable: false
            length: 3
            options:
                fixed: false
            column: FaxAreaCode
        faxnumber:
            type: string
            nullable: false
            length: 12
            options:
                fixed: false
            column: FaxNumber
        companytype:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CompanyType
        companyid:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: CompanyID
        defaultcustomer:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: DefaultCustomer
        defaultcashier:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: DefaultCashier
        defaultincomevat:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: DefaultIncomeVAT
        defaultincome:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: DefaultIncome
        logoimage:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: LogoImage
        dateCreated:
            type: datetime
            nullable: false
            column: date_created
        showCompanyOnline:
            type: boolean
            nullable: false
            column: show_company_online
        description:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        stamddate:
            type: datetime
            nullable: true
            column: StamdDate
        stampdevice:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: StampDevice
        swdelete:
            type: boolean
            nullable: false
            column: SwDelete
        sftpPassword:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: sftp_password
        sftpUrl:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: sftp_url
        sftpUsername:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: sftp_username
        amoCrmDomain:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: amo_crm_domain
        amoCrmKey:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: amo_crm_key
        amoCrmLogin:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: amo_crm_login
        defaultitem:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: DefaultItem
        bankaccount:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: BankAccount
        companyregister:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: CompanyRegister
        registercode:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: RegisterCode
        sharecapital:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: ShareCapital
        defaultunit:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: DefaultUnit
        defaultimporter:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: DefaultImporter
        defaultmanufacturer:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: DefaultManufacturer
        includeVat:
            type: boolean
            nullable: false
            column: include_vat
        barcodeType:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: barcode_type
        paymentType:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: payment_type
        website:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
            column: WebSite
        views:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
    lifecycleCallbacks: {  }
