AppBundle\Entity\Menu:
    repositoryClass: AppBundle\Entity\MenuRepository
    type: entity
    table: menu
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: name
    lifecycleCallbacks: {  }
