AppBundle\Entity\PostAttributes:
    repositoryClass: AppBundle\Entity\PostAttributesRepository
    type: entity
    table: post_attributes
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
